:proxallium_version: v0.4.1
:tor_version: 0.4.0.5

:tuxfamily_baseurl: https://download.tuxfamily.org/proxallium/releases/{proxallium_version}/ProxAllium-{proxallium_version}_Tor-{tor_version}
:github_baseurl: https://github.com/DcodingTheWeb/ProxAllium/releases/download/{proxallium_version}/ProxAllium-{proxallium_version}_Tor-{tor_version}

== Download ProxAllium

ProxAllium is made for Windows and it should work with Windows XP and above.

The latest version of ProxAllium is image:https://img.shields.io/github/release/DcodingTheWeb/ProxAllium/all.svg[{proxallium_version},link="https://github.com/DcodingTheWeb/ProxAllium/releases/tag/{proxallium_version}"] with image:https://img.shields.io/badge/Tor-{tor_version}-8A5BA3.svg[Tor {tor_version}].

[id=thanks]
--
*Thank you for using ProxAllium!* This will be the final release which is written in AutoIt, I am planning to re-write it in C and make it cross-platform.

However I can hardly take time out for my personal projects as I am busy working as a freelance software developer full time now, please consider link:../donate[donating] to support the development costs and encourage further development.

You can also share ProxAllium with your friends and family, the more the better! My main motivation are my users 😄
--

Download ProxAllium from these mirrors:

. {tuxfamily_baseurl}.7z[Download from Tux Family] ({tuxfamily_baseurl}.7z.sha256[SHA256]) ({tuxfamily_baseurl}.7z.asc[OpenPGP Signature])
. {github_baseurl}.7z[Download from GitHub] ({github_baseurl}.7z.sha256[SHA256]) ({github_baseurl}.7z.asc[OpenPGP Signature])

You should get a `7z` archive with all of the necessary files required to get ProxAllium running. We recommend using http://7-zip.org[7-zip] to extract the archive! All of the archives are signed, you can find the public key for verification https://dtw.tools/key.asc[here].

If you are looking for older versions, you can find them at https://github.com/DcodingTheWeb/ProxAllium/releases[GitHub's releases page] for ProxAllium or you can browse the https://download.tuxfamily.org/proxallium/releases/[download repository] for ProxAllium at TuxFamily. (These folks even provide ftp://download.tuxfamily.org/proxallium/releases[FTP] access!)

++++
<style>
/* "Thank You" message styles */
#thanks {
	color: #E0115F;
	padding: 5px;
	border: solid 2px #115fe0;
	border-radius: 10px;
	margin: 5px;
	margin-bottom: 20px;
}

/* Hide the table's style */
#changelog tbody > tr > td {
	padding: 0px;
	border: 0px;
}

/* Stylize the content container */
#changelog tbody > tr > td > div {
	max-height: 750px;
	overflow: auto;
	padding: 10px;
	border: 2px solid;
}
</style>
++++

[id="changelog"]
|===
a|
include::content\changelog.adoc[leveloffset=+1]
|===
